const UPDATEFACEDETECTED = "UPDATEFACEDETECTED"
const UPDATEYESDETECTED = "UPDATEYESDETECTED"
const UPDATENUMOFFACES = "UPDATENUMOFFACES"
const CHANGETHEME = "CHANGETHEME"
const SETUSER = "SETUSER"
const SETUSERPHOTO = "SETUSERPHOTO"
const CHANGE_PAGE = "CHANGE_PAGE"
export {
    UPDATEFACEDETECTED,
    UPDATENUMOFFACES,
    UPDATEYESDETECTED,
    CHANGETHEME,
    SETUSER,
    SETUSERPHOTO,
    CHANGE_PAGE
}